django-for-everybody/mysite/cats/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'cats'

urlpatterns = [
    path('', views.CatList.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('lookup/', views.BreedList.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),
]

# Note that make_ and auto_ give us uniqueness within this application

django-for-everybody/mysite/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Breed(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Breed must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Cat(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

django-for-everybody/mysite/cats/forms.py
from django.forms import ModelForm
from cats.models import Breed


# Create the form class.
class MakeForm(ModelForm):
    class Meta:
        model = Breed
        fields = '__all__'

django-for-everybody/mysite/cats/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from cats.models import Breed, Cat
from cats.forms import MakeForm

# Create your views here.


class CatList(LoginRequiredMixin, View):
    def get(self, request):
        mc = Breed.objects.all().count()
        al = Cat.objects.all()

        ctx = {'make_count': mc, 'cat_list': al}
        return render(request, 'cats/auto_list.html', ctx)


class BreedList(LoginRequiredMixin, View):
    def get(self, request):
        ml = Breed.objects.all()
        ctx = {'breed_list': ml}
        return render(request, 'cats/make_list.html', ctx)


# We use reverse_lazy() because we are in "constructor attribute" code
# that is run before urls.py is completely loaded
class BreedCreate(LoginRequiredMixin, View):
    template = 'cats/make_form.html'
    success_url = reverse_lazy('cats:all')

    def get(self, request):
        form = MakeForm()
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request):
        form = MakeForm(request.POST)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)

        make = form.save()
        return redirect(self.success_url)


# MakeUpdate has code to implement the get/post/validate/store flow
# AutoUpdate (below) is doing the same thing with no code
# and no form by extending UpdateView
class BreedUpdate(LoginRequiredMixin, View):
    model = Breed
    success_url = reverse_lazy('cats:all')
    template = 'cats/make_form.html'

    def get(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = MakeForm(instance=make)
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = MakeForm(request.POST, instance=make)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)

        form.save()
        return redirect(self.success_url)


class BreedDelete(LoginRequiredMixin, View):
    model = Breed
    success_url = reverse_lazy('cats:all')
    template = 'cats/make_confirm_delete.html'

    def get(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = MakeForm(instance=make)
        ctx = {'make': make}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        make.delete()
        return redirect(self.success_url)


# Take the easy way out on the main table
# These views do not need a form because CreateView, etc.
# Build a form object dynamically based on the fields
# value in the constructor attributes
class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')


class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')


class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

# We use reverse_lazy rather than reverse in the class attributes
# because views.py is loaded by urls.py and in urls.py as_view() causes
# the constructor for the view class to run before urls.py has been
# completely loaded and urlpatterns has been processed.

# References

# https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-editing/#createview

django-for-everybody/mysite/cats/templates/cats/auto_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Cat</h1>

<p>Are you sure you want to delete the cats: {{ cat }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

django-for-everybody/mysite/cats/templates/cats/auto_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Cats List</h1>
  {% if cat_list %}
  <ul>
    {% for cat in cat_list %}
      <li>
          {{ cat.nickname }} ({{ cat.breed }})
          (<a href="{% url 'cats:cat_update' cat.id %}">Update</a> |
          <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>) <br/>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no cats in the db.</p>
  {% endif %}
  <p>
    {% if make_count > 0 %}
      <a href="{% url 'cats:cat_create' %}">Add a cat</a>
    {% else %}
      Please add a Breed before you add a Cat.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'cats:breed_list' %}">View breeds</a> ({{ make_count }}) | 
    <a href="{% url 'cats:breed_create' %}">Add a breed</a>
  </p>
{% endblock %}

django-for-everybody/mysite/cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

django-for-everybody/mysite/cats/templates/cats/make_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Breed</h1>

<p>Are you sure you want to delete the breed: {{ breed }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

django-for-everybody/mysite/cats/templates/cats/make_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

django-for-everybody/mysite/cats/templates/cats/make_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Breed List</h1>
  {% if breed_list %}
  <ul>
    {% for breed in breed_list %}
      <li>
          {{ breed.name }}
         (<a href="{% url 'cats:breed_update' breed.id %}">Update</a> |
          <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no breed in the db.</p>
  {% endif %}
  <p><a href="{% url 'cats:breed_create' %}">Add a Breed</a></p>
  <p>
    <a href="{% url 'cats:all' %}">Back to Cats</a>
  </p>
{% endblock %}